// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfajIWB8H4vCvBEpxPpc8WK3Lsja5Qa84',
    appId: '1:117142388791:web:0f7784e0c4a487f4c43fb2',
    messagingSenderId: '117142388791',
    projectId: 'foodly-e7718',
    authDomain: 'foodly-e7718.firebaseapp.com',
    storageBucket: 'foodly-e7718.firebasestorage.app',
    measurementId: 'G-SENHW3QNVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO1P8iZL3zu0HpVW2qD0zFK23lYxi-GHA',
    appId: '1:117142388791:android:1f6aa0023322f86cc43fb2',
    messagingSenderId: '117142388791',
    projectId: 'foodly-e7718',
    storageBucket: 'foodly-e7718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpLzfsJFHEQbeHugkJLkrYqEmOIOFhJGE',
    appId: '1:117142388791:ios:6d5a949ed9f0aaebc43fb2',
    messagingSenderId: '117142388791',
    projectId: 'foodly-e7718',
    storageBucket: 'foodly-e7718.firebasestorage.app',
    iosBundleId: 'com.nexusinfinity.foodly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpLzfsJFHEQbeHugkJLkrYqEmOIOFhJGE',
    appId: '1:117142388791:ios:6d5a949ed9f0aaebc43fb2',
    messagingSenderId: '117142388791',
    projectId: 'foodly-e7718',
    storageBucket: 'foodly-e7718.firebasestorage.app',
    iosBundleId: 'com.nexusinfinity.foodly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfajIWB8H4vCvBEpxPpc8WK3Lsja5Qa84',
    appId: '1:117142388791:web:4e3cc078c2d32183c43fb2',
    messagingSenderId: '117142388791',
    projectId: 'foodly-e7718',
    authDomain: 'foodly-e7718.firebaseapp.com',
    storageBucket: 'foodly-e7718.firebasestorage.app',
    measurementId: 'G-C73B7Q1J0W',
  );
}
